# Generated by Django 4.1.7 on 2023-03-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.FloatField(max_length=255)),
                ('stock', models.ImageField(upload_to='')),
                ('image', models.CharField(max_length=3000)),
            ],
        ),
    ]
