# Generated by Django 4.1.7 on 2023-03-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('offer', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=4000)),
            ],
        ),
    ]
